// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otcwboloqarssmqvjpsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Y3dib2xvcWFyc3NtcXZqcHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzI0MTIsImV4cCI6MjA2Njk0ODQxMn0.Qis0Ru8AWc9wFJGT5cNOnwM9jIjqmUtBrbhhDyFkVEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);